const img = (name: string) => `/img/hendrawan-larasati/${name}.jpg`;

export const invitation = {
  slug: "hendrawan-larasati",
  monogram: "H & L",
  collection: "No. 0508",
  groom: {
    name: "Hendrawan",
    full: "Hendrawan Putra",
    parents: "Bapak Made Suardana & Ibu Ketut Sriani",
    role: "Putra dari",
    photo: img("groom"),
    flower: "cempaka",
    latin: "Magnolia champaca",
  },
  bride: {
    name: "Larasati",
    full: "Larasati Dewi",
    parents: "Bapak Wayan Artawan & Ibu Nyoman Suarni",
    role: "Putri dari",
    photo: img("bride"),
    flower: "anggrek bulan",
    latin: "Phalaenopsis amabilis",
  },
  latinPair: "Magnolia & Phalaenopsis",
  date: "2027-05-08T09:00:00+08:00",
  end: "2027-05-08T15:00:00+08:00",
  dayLabel: "Sabtu",
  dateShort: "08 . 05 . 2027",
  dateLong: "Sabtu, 8 Mei 2027",
  place: "Ubud, Bali",
  tz: "WITA",
  events: [
    { time: "09.00", name: "Upacara Pernikahan" },
    { time: "12.00", name: "Resepsi", until: "15.00" },
  ],
  venue: {
    name: "Taman Sari Kembang",
    address: "Jl. Raya Ubud No. 18, Gianyar, Bali",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=Ubud+Bali",
  },
  rsvpDeadline: "24 April 2027",
  honor:
    "Merupakan suatu kehormatan dan kebahagiaan bagi kami apabila Bapak/Ibu/Saudara/i berkenan hadir dan memberikan doa restu.",
  quote: "Seperti bunga yang disimpan di antara halaman buku, kami ingin menyimpan hari ini selamanya.",
  images: {
    hero: img("hero"),
    heroWide: img("hero-wide"),
    venue: img("venue"),
    grain: "/img/hendrawan-larasati/grain.webp",
    qris: "/img/hendrawan-larasati/qris.png",
    og: "/img/hendrawan-larasati/og.jpg",
  },
  music: "/img/hendrawan-larasati/music.mp3",
  specimens: [
    { src: img("spec-1"), w: 600, h: 589, latin: "Rosa chinensis", local: "mawar", no: "042" },
    { src: img("spec-2"), w: 600, h: 600, latin: "Phalaenopsis amabilis", local: "anggrek bulan", no: "057" },
    { src: img("spec-3"), w: 600, h: 675, latin: "Rosa & Phalaenopsis", local: "buket pengantin", no: "063" },
    { src: img("spec-4"), w: 600, h: 436, latin: "Phalaenopsis amabilis", local: "anggrek putih", no: "071" },
  ],
  story: [
    {
      title: "Pertama Bertemu",
      date: "14.02.2020",
      no: "014",
      place: "Denpasar",
      image: img("story-1"),
      short: "Dua orang di gerbang yang sama, menunggu hujan reda.",
      long: "Kami berteduh di gerbang bata yang sama saat hujan sore turun tanpa aba-aba. Larasati membawa payung, Hendrawan tidak. Sejak itu, kami selalu pulang ke arah yang sama.",
    },
    {
      title: "Tumbuh Bersama",
      date: "03.06.2022",
      no: "027",
      place: "Ubud",
      image: img("story-2"),
      short: "Belajar merawat satu sama lain, pelan dan sabar.",
      long: "Seperti merawat tanaman di halaman rumah, kami belajar bahwa yang tumbuh baik adalah yang dirawat setiap hari, bukan hanya saat sedang mekar.",
    },
    {
      title: "Lamaran",
      date: "21.12.2025",
      no: "031",
      place: "Gianyar",
      image: img("story-3"),
      short: "Di balik pintu kayu berukir, satu pertanyaan dan satu jawaban.",
      long: "Di depan kedua keluarga, di balik pintu kayu berukir rumah nenek, Hendrawan bertanya. Larasati menjawab dengan anggukan, lalu dengan tawa.",
    },
    {
      title: "Hari Pernikahan",
      date: "08.05.2027",
      no: "0508",
      place: "Ubud",
      image: img("story-4"),
      short: "Lembar terbaru dalam koleksi kami, dan kalian ada di dalamnya.",
      long: "Payung tedung sudah terpasang, bunga sudah dirangkai. Hari ini kami simpan sebagai lembar paling berharga, bersama doa dari kalian semua.",
    },
  ],
  gallery: [
    { src: img("g-1"), w: 1200, h: 1530, alt: "Hendrawan dan Larasati berdiri di depan pintu ukir", caption: "di depan pintu ukir", no: "102" },
    { src: img("g-4"), w: 1200, h: 1012, alt: "Hendrawan dan Larasati tersenyum di depan pintu kayu", caption: "senyum pagi", no: "108" },
    { src: img("g-3"), w: 1200, h: 1080, alt: "Hendrawan dan Larasati duduk di gerbang pura dengan payung tedung", caption: "payung tedung", no: "115" },
    { src: img("g-6"), w: 1200, h: 900, alt: "Hendrawan dan Larasati saling menatap di taman", caption: "taman belakang", no: "121" },
    { src: img("g-5"), w: 1200, h: 1620, alt: "Hendrawan dan Larasati berpelukan di balik pintu kayu", caption: "di balik pintu", no: "129" },
    { src: img("g-2"), w: 1400, h: 933, alt: "Hendrawan dan Larasati di gerbang bata", caption: "gerbang bata", no: "134" },
  ],
  gifts: [
    { bank: "Bank Contoh", number: "0000 5555 0808", holder: "Hendrawan Putra" },
    { bank: "Bank Contoh", number: "2222 7777 0808", holder: "Larasati Dewi" },
  ],
  sampleWishes: [
    { id: "hl-sample-1", name: "Keluarga Besar Suardana", message: "Rahajeng nganten anyar. Semoga menjadi keluarga yang rukun dan bahagia selamanya." },
    { id: "hl-sample-2", name: "Komang", message: "Akhirnya lembar ini terisi juga. Selamat, Hendra dan Laras!" },
    { id: "hl-sample-3", name: "Bu Ayu", message: "Semoga cinta kalian terus mekar seperti kembang di halaman rumah." },
    { id: "hl-sample-4", name: "Teman Kantor Larasati", message: "Selamat menempuh hidup baru. Ditunggu cerita-cerita selanjutnya." },
  ],
} as const;

export type Invitation = typeof invitation;
